name: SimpleBuild
on: 
  push:
    paths: 
      - "**.ino"
      - "**.cpp"
  pull_request:
    paths: 
      - "**.ino"
      - "**.cpp"
jobs:
  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2
