name: Build examples
on: 
  push:
    paths: 
      - '**.ino'
  pull_request:
    paths: 
      - '**.ino'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all example sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:uno"
